### ISSUE TITLE
curl client does not receive the full body

### ISSUE THREAD

**Issue by CryZe** [rustasync/surf#36]
It seems like the curl based client does not wait until all the data is received, which can make it fail deserializing when the response is too large.

The code is roughly this, but this is not the actual URL as its a private gitlab instance:
```rust
    let response: Vec<Project> = surf::get("http://gitlab.com/api/v4/projects")
        .recv_json()
        .await
        .unwrap();
```

The response suddenly ends like this:
```
"star_count":100,"forks_count":2,"last_activity_at":"2019-07-02T08:41:28.976Z","namespace":{"id":999,"name":"r
```

**Comment by Byron** [comment]
I am hitting the same issue. Here is a one-liner to reproduce it :).

```
git clone --branch surf-bug https://github.com/Byron/github-star-counter && cd github-star-counter && cargo run  -- --log-level INFO seanmonstar
```

**Comment by yoshuawuyts** [comment]
@CryZe @Byron thanks for the report. Investigating!

**Comment by yoshuawuyts** [comment]
Okay, just ran this with the `Hyper` backend, and confirmed it's also happening there.

![2019-08-16-145135_1920x1080](https://user-images.githubusercontent.com/2467194/63168764-54cc8500-c035-11e9-9233-c848c4cf5478.png)

The next test is to see if this might be related to the runtime that's driving the futures.

**Comment by Byron** [comment]
Wow, fantastic reporting style - screenshots are awesome!

Glad you could already exclude the backend! Fingers crossed you find it
quickly!

**Comment by yoshuawuyts** [comment]
Dang okay, I'm having a bit of trouble porting the code because something is not implementing `Send` where other runtimes are expecting it -- but I can't quite figure out what.

Also  I've been running against rate limits, and given my security settings on github it's a bit annoying to work against. I'm going to try and see if I can query a big json blob from somewhere else, and use that to run an mvp against so we can debug this.

**Comment by Byron** [comment]
It’s easy to workaround the rate limits if you just have a personal access
token curtesy of your github account. `count-github-stars` allows to pass
this using the  —request-username and —request-password flags, and the
error message you see points to a resource on how to get that token.

Maybe it helps that the previous implementation, on `master` of the
`github-star-counter` repository used a custom reader that would manage to
get chunks from `hyper`. Maybe entirely unrelated though... .

**Comment by yoshuawuyts** [comment]
Wrote a quick local repro using a non-tokio runtime. It turns out the request body terminates with quite consistent response length numbers:

- 49047
- 65431
- 32663 (only once)

![2019-08-16-154755_1920x1080](https://user-images.githubusercontent.com/2467194/63172063-1dfa6d00-c03d-11e9-9118-163bd13261f7.png)

This seems to point we're aborting the internal body stream too early somewhere.

**Comment by yoshuawuyts** [comment]
Okay, it seems `chttp`/`isahc` stops reading bytes because the client is terminated.

![2019-08-16-155816_1920x1080](https://user-images.githubusercontent.com/2467194/63172744-adece680-c03e-11e9-9c23-ad7df32c7c76.png)

**Comment by yoshuawuyts** [comment]
Okay, re-ran it with `hyper` again (used #34), and this time around it *does* work! This is with the default `runtime` (though I suspect that may not be the problem right now).

## Repro code

__main.rs__
```rust
#![feature(async_await)]

#[runtime::main]
async fn main() {
    femme::start(log::LevelFilter::Info).unwrap();
    let string = surf::get("http://localhost:8080")
        .recv_string()
        .await
        .unwrap();
    dbg!(&string);
    println!("received {} bytes", string.len());
}
```

__index.js__
```js
var http = require('http')

http.createServer((req, res) => {
  var body = []
  for (let i = 0, j = 100000; i < j; i++) {
    body.push({ message: 'hello world' })
  }
  res.end(JSON.stringify(body))
}).listen(8080, () => console.log('listening on port 8080'))
```

## Screenshot
![2019-08-16-160739_1920x1080](https://user-images.githubusercontent.com/2467194/63173295-e17c4080-c03f-11e9-8b76-1f6394ff5bb0.png)

## Repro
https://github.com/yoshuawuyts/repro-surf-36

---

cc/ @sagebind, do you have any idea what might be going wrong here?

**Comment by sagebind** [comment]
@yoshuawuyts I think this assessment is most accurate:

> Okay, it seems chttp/isahc stops reading bytes because the client is terminated.

Your `chttp::Client` is being dropped after you receive the response headers, but during the middle of tranferring the response stream. This happens because awaiting a `Request` consumes self and returns a `Response` after the response headers are received. Since the `Request` is dropped, the `HttpClient` is also dropped.

https://github.com/rustasync/surf/blob/d7d9d054aad0a9bc46a7d177e133770c25451c6a/src/request.rs#L575-L582

Since all we have left on the stack is a `http::Response<Body>` after executing the request, the `HttpClient` is no longer alive to finish the transfer of the response body.

There's some interesting questions here on how the lifetime of an `HttpClient` should interact with a `Body`, but either way, Isahc clients should probably keep themselves alive in the background until all active transfers either finish or are cancelled (dropping a `chttp::Body` is enough to signal cancellation). I opened a bug on Isahc here: https://github.com/sagebind/isahc/issues/64

**Comment by CarlosLanderas** [comment]
+1 Im having the same problem

**Comment by sagebind** [comment]
The upstream Isahc bug has been fixed, so updating the version Surf uses should fix the problem.

**Comment by CarlosLanderas** [comment]
I still see version 1.0.1 published 7 days ago. When is next version going to be published to crates.io?
Thanks!

**Comment by berkus** [comment]
Also haunted by this issue, when will the next version be published? This looks like a critical fix to me.

**Comment by berkus** [comment]
This should be fixed now that #49 is merged.

**Comment by berkus** [comment]
> The upstream Isahc bug has been fixed, so updating the version Surf uses should fix the problem.

This should be fixed now that #49 is merged.

**Comment by CarlosLanderas** [comment]
As surf version 1.0.1 uses former chttp and the fix was released under new isahc crate, is there any plan to update surf version anytime soon to have this fix?

Thanks

**Comment by CarlosLanderas** [comment]
Looks fixed for me. First time I retrieve a 300kbs file :). Thanks!
